name: Build and push

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Push to is-a.dev repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
        with:
          source-directory: 'build'
          destination-github-username: 'legendsayantan'
          destination-repository-name: 'legendsayantan.is-a.dev'
          target-branch: main
      - name: Setup workflows on is-a.dev repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{secrets.API_TOKEN_GITHUB}}
        with:
          source-directory: .push/.github/
          target-directory: .github/
          destination-github-username: 'legendsayantan'
          destination-repository-name: 'legendsayantan.is-a.dev'
          target-branch: main